title: SA4S Deadlines
description: Countdowns to top Software Engineering deadlines.
author: Sivana Hamer, Imranur Rahman, Shrikara A

domain: "sa4s-deadlines.github.io"
baseurl: ""

github_username: sa4s-deadlines
github_repo: sa4s-deadlines.github.io

markdown: kramdown
